/**
 * UDYOG Centralized Language & Voice Configuration
 * 
 * Maps all 22 scheduled Indian languages + English to:
 * - Real VEXYL / Indic Parler-TTS language codes and female voice presets
 * - TTS availability (honestly distinguished: 21 languages supported, Kashmiri unsupported)
 * - Directionality (RTL for Urdu and Kashmiri)
 * - Fallback behavior
 */

export interface LanguageVoiceConfig {
  code: string; // ISO 639-1 / 639-2 (e.g. 'ta', 'hi', 'ks')
  locale: string; // BCP-47 locale (e.g. 'ta-IN')
  name: string; // English name (e.g. 'Tamil')
  nativeName: string; // Native script name (e.g. 'தமிழ்')
  direction: 'ltr' | 'rtl';
  ttsProvider: 'vexyl' | 'none';
  vexylLangCode: string | null; // e.g. 'ta-IN' or null if unsupported
  femaleVoice: string; // e.g. 'Jaya', 'Divya', 'Aisha'
  defaultStyle: 'default' | 'warm' | 'formal';
  ttsAvailable: boolean; // Truthful model support flag
  fallbackNotice?: string;
}

export const LANGUAGE_VOICE_CATALOG: Record<string, LanguageVoiceConfig> = {
  ta: {
    code: 'ta',
    locale: 'ta-IN',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'ta-IN',
    femaleVoice: 'Jaya',
    defaultStyle: 'formal',
    ttsAvailable: true,
  },
  hi: {
    code: 'hi',
    locale: 'hi-IN',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'hi-IN',
    femaleVoice: 'Divya',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  ml: {
    code: 'ml',
    locale: 'ml-IN',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'ml-IN',
    femaleVoice: 'Anjali',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  te: {
    code: 'te',
    locale: 'te-IN',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'te-IN',
    femaleVoice: 'Lalitha',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  kn: {
    code: 'kn',
    locale: 'kn-IN',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'kn-IN',
    femaleVoice: 'Anu',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  bn: {
    code: 'bn',
    locale: 'bn-IN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'bn-IN',
    femaleVoice: 'Aditi',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  gu: {
    code: 'gu',
    locale: 'gu-IN',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'gu-IN',
    femaleVoice: 'Neha',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  mr: {
    code: 'mr',
    locale: 'mr-IN',
    name: 'Marathi',
    nativeName: 'मराठी',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'mr-IN',
    femaleVoice: 'Sunita',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  pa: {
    code: 'pa',
    locale: 'pa-IN',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'pa-IN',
    femaleVoice: 'Divjot',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  or: {
    code: 'or',
    locale: 'or-IN',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'or-IN',
    femaleVoice: 'Debjani',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  as: {
    code: 'as',
    locale: 'as-IN',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'as-IN',
    femaleVoice: 'Sita',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  ur: {
    code: 'ur',
    locale: 'ur-IN',
    name: 'Urdu',
    nativeName: 'اردو',
    direction: 'rtl',
    ttsProvider: 'vexyl',
    vexylLangCode: 'ur-IN',
    femaleVoice: 'Zainab',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  ne: {
    code: 'ne',
    locale: 'ne-IN',
    name: 'Nepali',
    nativeName: 'नेपाली',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'ne-IN',
    femaleVoice: 'Amrita',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  sa: {
    code: 'sa',
    locale: 'sa-IN',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'sa-IN',
    femaleVoice: 'Vasudha',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  brx: {
    code: 'brx',
    locale: 'brx-IN',
    name: 'Bodo',
    nativeName: 'बर’',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'brx-IN',
    femaleVoice: 'Bimala',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  doi: {
    code: 'doi',
    locale: 'doi-IN',
    name: 'Dogri',
    nativeName: 'डोगरी',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'doi-IN',
    femaleVoice: 'Meena',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  kok: {
    code: 'kok',
    locale: 'kok-IN',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'kok-IN',
    femaleVoice: 'Priya',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  mai: {
    code: 'mai',
    locale: 'mai-IN',
    name: 'Maithili',
    nativeName: 'मैथिली',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'mai-IN',
    femaleVoice: 'Shruti',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  mni: {
    code: 'mni',
    locale: 'mni-IN',
    name: 'Manipuri',
    nativeName: 'মৈতৈলোন্',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'mni-IN',
    femaleVoice: 'Leima',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  sat: {
    code: 'sat',
    locale: 'sat-IN',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'sat-IN',
    femaleVoice: 'Sumitra',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  sd: {
    code: 'sd',
    locale: 'sd-IN',
    name: 'Sindhi',
    nativeName: 'سنڌي',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'sd-IN',
    femaleVoice: 'Hema',
    defaultStyle: 'default',
    ttsAvailable: true,
  },
  ks: {
    code: 'ks',
    locale: 'ks-IN',
    name: 'Kashmiri',
    nativeName: 'کٲشُر',
    direction: 'rtl',
    ttsProvider: 'none',
    vexylLangCode: null,
    femaleVoice: 'Aisha',
    defaultStyle: 'default',
    ttsAvailable: false, // Honestly flagged: Indic Parler-TTS does not support Kashmiri
    fallbackNotice: 'Voice support for this language is currently unavailable. You can continue using text.',
  },
  en: {
    code: 'en',
    locale: 'en-IN',
    name: 'English',
    nativeName: 'English',
    direction: 'ltr',
    ttsProvider: 'vexyl',
    vexylLangCode: 'en-IN',
    femaleVoice: 'Aisha',
    defaultStyle: 'formal',
    ttsAvailable: true,
  },
};

/**
 * Normalizes any language code or locale into standard configuration
 */
export function getLanguageVoiceConfig(langCode: string): LanguageVoiceConfig {
  if (!langCode) return LANGUAGE_VOICE_CATALOG.en;
  const baseCode = langCode.split('-')[0].toLowerCase();
  return LANGUAGE_VOICE_CATALOG[baseCode] || LANGUAGE_VOICE_CATALOG[langCode.toLowerCase()] || LANGUAGE_VOICE_CATALOG.en;
}
